### ISSUE TITLE
RPCS3 plugin not tracking time on GOG v2.0.11.2

### ISSUE THREAD

**Issue by adb0t** [mpm11011/galaxy-integration-rpcs3#19]
I ran the RPCS3 game from GOG 2 client as said from previous issue posted here.
It did not also record achievement.

**Logs**

[GalaxyClient.txt](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3949786/GalaxyClient.txt)

[plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.txt](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3949748/plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.txt)

[config.py.txt](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3949793/config.py.txt)

**Comment by massimilianodelliubaldini** [comment]
There seems to be an issue with game time recording for sure:

```
2019-12-11 18:05:53,316 - root - ERROR - Unexpected exception raised in plugin tick
Traceback (most recent call last):
  File "C:\Users\engr\AppData\Local\GOG.com\Galaxy\plugins\installed\vision_80F9D16B-5D72-4B95-9D46-2A1EF417C1FC\galaxy\api\plugin.py", line 201, in _pass_control
    self.tick()
  File "C:\Users\engr\AppData\Local\GOG.com\Galaxy\plugins\installed\vision_80F9D16B-5D72-4B95-9D46-2A1EF417C1FC\plugin.py", line 167, in tick
    int(time.time()))
  File "C:\Users\engr\AppData\Local\GOG.com\Galaxy\plugins\installed\vision_80F9D16B-5D72-4B95-9D46-2A1EF417C1FC\plugin.py", line 223, in update_json_game_time
    game_times_json = json.load(game_times_file)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\__init__.py", line 296, in load
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\__init__.py", line 348, in loads
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\decoder.py", line 337, in decode
  File "**D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\decoder.py**", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 18 (char 19)
```

But I'm not sure what that indicates. Can you tell me about the nature of your python installation? Is it on a separate volume (e.g. D:) than Windows (C:)?

However, it seems achievements are being recorded:

```
2019-12-11 16:29:51,514 - root - INFO - Sending notification: method=game_achievements_import_success, params={'game_id': 'NPUA80637', 'unlocked_achievements': [Achievement(unlock_time=0, achievement_id=None, achievement_name='Swing Batter'), Achievement(unlock_time=0, achievement_id=None, achievement_name='Two Girls One Spartan'), Achievement(unlock_time=0, achievement_id=None, achievement_name='Man Overboard'), Achievement(unlock_time=0, achievement_id=None, achievement_name='Persian History X'), Achievement(unlock_time=0, achievement_id=None, achievement_name='All Beam Walks Completed')]}
```

Can you tell me what game and achievement you're having trouble with? That might help me narrow down where in your logs it could be.

**Comment by adb0t** [comment]
I do not remember installing any python on my computer. I just downloaded your plugin and I also tried to trace "D:\obj\.." and I do not see any "obj" folder on my drive D:. Also, this will help for sure, I am not a coding guy.

On recording of achievements on GOG 2.. I opened the library and it seems the achievements does not display especially when I clicked the "My Progress". It does not show any game time and achievements.. so maybe it is another issue.

EDIT:
The game is God of War: Chains of Olympus and the achievment I am having trouble with is any achievement I got on the game in RPCS3 does not reflect on GOG 2 client.

![erw](https://user-images.githubusercontent.com/21361363/71166111-ff2b1200-228c-11ea-9116-558c03d6837f.png)


EDIT2:
Tried to search Python and Open the file location, here is the directory:
C:\Users\engr\AppData\Local\Microsoft\WindowsApps

**Comment by GKontizas** [comment]
Hello!

I'm having a similar issue. Not only it does not detect game time or the trophies, but every game I launch is not being registered as being played (for example it is not shown in the recent tab).

Here is a picture of Demon's Souls that I've been playing recently. Is this the expected behavior of the plugin? (considering I've unlocked some trophies and played for 20 hours)
![rpcs3gog](https://user-images.githubusercontent.com/43218788/72610702-bcfafc00-3930-11ea-8a7e-a60ca282cd4f.png)

Despite this issue thank you so much everyone involved in this plugin, GOG Galaxy and the RPCS3 team. As much as I like Demon's Souls on my PS3, it's much better dumping it to my PC and playing it there. (love redoing the trophies, wish they showed up)
